### ISSUE TITLE
Component to select year

### ISSUE THREAD

**Issue by jsergiu** [code4romania/sna-client#11]
![image](https://cloud.githubusercontent.com/assets/4572368/23632777/8015d18a-02c3-11e7-8d16-50601a37ad33.png)

**Comment by vitaliel** [comment]
@jsergiu putem accepta modelul de mai jos sau tre să fie ca în design?
![select_year](https://cloud.githubusercontent.com/assets/995/23987673/5ed4d4d6-0a33-11e7-8c2e-a70b77f4cb7c.png)

**Comment by jsergiu** [comment]
Putem lasa asa deocamdata. Se poate adauga cate un label pt fiecare an dedesupt?

**Comment by vitaliel** [comment]
Pentru label la fiece an e necesar de modificat componentul react-bootstrap-slider să folosească tick label, exemplul 13
http://seiyria.com/bootstrap-slider/

**Comment by jsergiu** [comment]
vad ca suporta deja ceva de genu: 
![image](https://cloud.githubusercontent.com/assets/4572368/23990118/4dfd4b14-0a35-11e7-8de6-4cb338e685c4.png)

**Comment by vitaliel** [comment]
Păi da, dar componentul react nu spuportă...

**Comment by jsergiu** [comment]
Daca pui pur si simplu un div cu anii dedesupt? fara sa modifici componenta

**Comment by vitaliel** [comment]
I-am pus și labels.
