### ISSUE TITLE
Report page with graphs based on selected filters

### ISSUE THREAD

**Issue by jsergiu** [code4romania/sna-client#13]
![image](https://cloud.githubusercontent.com/assets/4572368/23632895/ebaa11b8-02c3-11e7-816e-cd9426c6c88c.png)

**Comment by vitaliel** [comment]
@LucianU @84colors 
Cum va arăta această pagină pentru județe și alte indicatoare(Declararea averilor, etc)?

**Comment by 84colors** [comment]
Maine o sa fie gata si screens pentru celelalte indicatore. Pentru judete, o sa ma uit mai atent in fisierul excel sa vad daca ar fi ceva diferit, dar in principiu o sa arate la fel.

**Comment by LucianU** [comment]
În ce stadiu e issue-ul ăsta?

**Comment by vitaliel** [comment]
Șablonul general pentru pagină e gata, trebuie doar date reale și de pus celelalte indicatoare.
