### ISSUE TITLE
Incidents count graph (nr sesizari)

### ISSUE THREAD

**Issue by jsergiu** [code4romania/sna-client#15]
![image](https://cloud.githubusercontent.com/assets/4572368/23632965/2a3dc2da-02c4-11e7-84d0-c2811af491a6.png)

**Comment by vitaliel** [comment]
Sample chart with recharts: http://jsfiddle.net/u8udorvy/234/

**Comment by vitaliel** [comment]
Este BarChart în https://github.com/code4romania/sna-client/pull/32
