### ISSUE TITLE
Dynamic scattered graph

### ISSUE THREAD

**Issue by jsergiu** [code4romania/sna-client#17]
![image](https://cloud.githubusercontent.com/assets/4572368/23633037/69e95340-02c4-11e7-9177-69eae19e923a.png)

**Comment by vitaliel** [comment]
Un prototip este în https://github.com/code4romania/sna-client/pull/32/commits/a42a184d62c500e882414edd56bc90bce9163cb4.

**Comment by LucianU** [comment]
E nevoie de ajutorul lui @84colors, aici?

**Comment by vitaliel** [comment]
nu.

**Comment by vitaliel** [comment]
Reparat în 8235c0f
