### ISSUE TITLE
Build #4 (Mar 28, 2017 8:36:08 AM)

### ISSUE THREAD

**Issue by octaviandavid** [code4romania/sna-client#37]
TASK [build : NPM build] *******************************************************
fatal: [34.249.150.177]: FAILED! => {"changed": true, "cmd": ["npm", "run", "build:prod"], "delta": "0:00:01.939338", "end": "2017-03-28 08:37:04.860007", "failed": true, "rc": 1, "start": "2017-03-28 08:37:02.920669", "stderr": "/jenkins/workspace/SNA/config/webpack/dev.js:1\n(function (exports, require, module, __filename, __dirname) { let path = require('path');\n                                                              ^^^\n\nSyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode\n    at exports.runInThisContext (vm.js:53:16)\n    at Module._compile (module.js:373:25)\n    at Object.Module._extensions..js (module.js:416:10)\n    at Module.load (module.js:343:32)\n    at Function.Module._load (module.js:300:12)\n    at Module.require (module.js:353:17)\n    at require (internal/module.js:12:17)\n    at Object.<anonymous> (/jenkins/workspace/SNA/config/webpack/index.js:6:20)\n    at Module._compile (module.js:409:26)\n    at Object.Module._extensions..js (module.js:416:10)\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno 1\nnpm ERR! sna-client@0.0.1 build: `webpack --config config/webpack/index.js`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the sna-client@0.0.1 build script 'webpack --config config/webpack/index.js'.\nnpm ERR! Make sure you have the latest version of node.js and npm installed.\nnpm ERR! If you do, this is most likely a problem with the sna-client package,\nnpm ERR! not with npm itself.\nnpm ERR! Tell the author that this fails on your system:\nnpm ERR!     webpack --config config/webpack/index.js\nnpm ERR! You can get information on how to open an issue for this project with:\nnpm ERR!     npm bugs sna-client\nnpm ERR! Or if that isn't available, you can get their info via:\nnpm ERR!     npm owner ls sna-client\nnpm ERR! There is likely additional logging output above.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /jenkins/.npm/_logs/2017-03-28T08_37_04_841Z-debug.log\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno 1\nnpm ERR! sna-client@0.0.1 build:prod: `cross-env NODE_ENV=production npm run clean && npm run build`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the sna-client@0.0.1 build:prod script 'cross-env NODE_ENV=production npm run clean && npm run build'.\nnpm ERR! Make sure you have the latest version of node.js and npm installed.\nnpm ERR! If you do, this is most likely a problem with the sna-client package,\nnpm ERR! not with npm itself.\nnpm ERR! Tell the author that this fails on your system:\nnpm ERR!     cross-env NODE_ENV=production npm run clean && npm run build\nnpm ERR! You can get information on how to open an issue for this project with:\nnpm ERR!     npm bugs sna-client\nnpm ERR! Or if that isn't available, you can get their info via:\nnpm ERR!     npm owner ls sna-client\nnpm ERR! There is likely additional logging output above.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /jenkins/.npm/_logs/2017-03-28T08_37_04_853Z-debug.log", "stdout": "\n> sna-client@0.0.1 build:prod /jenkins/workspace/SNA\n> cross-env NODE_ENV=production npm run clean && npm run build\n\n\n> sna-client@0.0.1 clean /jenkins/workspace/SNA\n> rimraf build\n\n\n> sna-client@0.0.1 build /jenkins/workspace/SNA\n> webpack --config config/webpack/index.js", "stdout_lines": ["", "> sna-client@0.0.1 build:prod /jenkins/workspace/SNA", "> cross-env NODE_ENV=production npm run clean && npm run build", "", "", "> sna-client@0.0.1 clean /jenkins/workspace/SNA", "> rimraf build", "", "", "> sna-client@0.0.1 build /jenkins/workspace/SNA", "> webpack --config config/webpack/index.js"], "warnings": []}
	to retry, use: --limit @/jenkins/workspace/Jenkins/sna.retry

**Comment by LucianU** [comment]
Pare să fi fost o problemă ce va fi rezolvată de `yarn`.
