### ISSUE TITLE
Lipsa indicii de utilizare

### ISSUE THREAD

**Issue by oliviavereha** [code4romania/sna-client#55]
cand ajung in homepage: https://sna.code4.ro/
nu exista nici un helper sa imi dau seama ce anume este pagina asta si cum o pot utiliza. 
As vrea ca sub Prezentare indicatori SNA sa mi se dea niste instructiuni, ceva de genul: 
- navigheaza prin meniul din stanga pentru a vedea care a fost evolutia indicatorilor de evaluare pe administratii, ministere etc

In momentul asta harta nu face nimic si daca eu intru pe site si dau click direct pe harta am impresia ca nu merge site-ul, pentru acolo e punctul meu de focalizare.

**Comment by LucianU** [comment]
Există niște tooltipuri, dar sunt afișate doar prima oară când intri pe pagină. Am putea să facem în așa fel încât să fie afișate de fiecare dată când intri, dar ar deveni agasante la un moment dat.
