### ISSUE TITLE
Vizibilitate grafica homepage

### ISSUE THREAD

**Issue by oliviavereha** [code4romania/sna-client#56]
Pe monitoare mai vechi harta nu se vede aproape deloc din cauza culorii. 
Putem sa incarcam o harta mai vizibila. Cineva cu un contrast prost nu o vede aproape deloc. trebuie sa luam in calcul ca nu toata lumea are monitoare bune si ca sunt multi oameni si cu dificultati de vedere.

**Comment by LucianU** [comment]
Te referi la harta care apare înainte să fie afișate statisticile?
