### ISSUE TITLE
Sageata nefunctionala

### ISSUE THREAD

**Issue by oliviavereha** [code4romania/sna-client#57]
Sageata din dreptul butonului de "INAPOI" nu functioneaza. Clickul are efect doar daca apas pe cuvant, nu si pe sageata.

**Comment by LucianU** [comment]
Păi săgeata nu e clickuibilă, doar butonul ÎNAPOI. Asta sugerează că săgeata are doar rol de simbol și că utilizatorul poate să dea click pe ÎNAPOI ca să se întoarcă de unde-a venit.
@calinrulz, tu ce părere ai despre asta?
