### ISSUE TITLE
Lipsa indicatii de content

### ISSUE THREAD

**Issue by oliviavereha** [code4romania/sna-client#58]
Lipsa unor indicii pentru persoanele neavizate. 
labelingul folosit in aplicatie nu este deloc intuitiv: 
"Indicator vizualizat" ar trebui sa fie schimbat in ceva de genul: "Da click si alege din lista de mai jos ce tip de indicator vrei sa vezi..."
As putea sa fac textele astea ca sa fie mai intuitive

**Comment by LucianU** [comment]
Nu știu ce să zic. Faptul că are o săgeata în dreapta care arată în jos îmi spune faptul că e un dropdown.
