### ISSUE TITLE
Lipsa Buton de Home

### ISSUE THREAD

**Issue by oliviavereha** [code4romania/sna-client#59]
Stiu ca in majoritatea aplicatiilor logo-ul este cel care te duce inapoi acasa, dar aici nu este foarte evident. 
As adauga un Buton de Home inainte de Despre aplicatie. 

Also, sna.just.ro va fi site-ul pe care va exista aplicatia SNA sau e alta?

**Comment by LucianU** [comment]
sna.just.ro e portalul celor de la SNA. Aplicația făcută de noi va sta la sna.just.ro/statistici sau ceva de genul ăsta.

Deci butonul acela din dreapta îți spune că poți să te întorci la portal dacă dai click pe el. Nu știu dacă n-ar stârni confuzie un buton de Home. Home ar însemna prima pagina aplicației ăsteia sau sna.just.ro? Faptul că scrie sna.just.ro face totul explicit.
