### ISSUE TITLE
Paginile fara date 

### ISSUE THREAD

**Issue by oliviavereha** [code4romania/sna-client#60]
Pentru unii indicatori nu exista date, dar nu semnalam asta deloc. Doar nu incarcam nimic in pagina respectiva si userul poate crede ca nu ii mai merge aplicatia. 

De exemplu: https://sna.code4.ro/report/1/1 , in pagina asta nu am niciun indiciu ca nu am reprezentari pentru ca nu exista date. Miar fi util sa am un mesaj, in locul in care in care in mod normal mi se listeaza Numar sesizari, ca nu exista date pentru acest indicator/aceasta categorie.

**Comment by LucianU** [comment]
Mie îmi apar date pentru indicatorul ăla. Totuși de acord că tre să afișăm un mesaj dacă nu există date.
@calinrulz, poți verifica dacă există un screen pentru situația în care nu avem date? Dacă nu există, poți să adaugi unul?
