### ISSUE TITLE
Footer nestandardizat

### ISSUE THREAD

**Issue by oliviavereha** [code4romania/sna-client#61]
Exista un standard la momentul asta de cum trebuie sa apara code4romania in Footer in aplicatiile pe care le facem.
Exemplu: http://inlar.org/en/

Logoul Code4Romania
Proiect realizat in colaborare cu Code for Romania. 
Organizație neguvernamentală independentă, neafiliată politic și apolitică.

**Comment by LucianU** [comment]
@calinrulz, poți schimba footerul, te rog?
