### ISSUE TITLE
Mobile version nefunctional

### ISSUE THREAD

**Issue by oliviavereha** [code4romania/sna-client#62]
La acest moment varianta de mobil nu functioneaza.
Tot ce pot sa fac este sa navighez prin meniu, dar nu mi se afiseaza deloc datele, indiferent de selectia pe care o fac.

**Comment by LucianU** [comment]
Am avut și eu aceeași problemă. Trebuie să închizi navigația ca să poți vedea vizualizările. Totuși sunt de acord că nu e intuitiv, din moment ce am avut aceeași problemă până mi-a explicat cineva.

@calinrulz, se poate să ascundem navigația după ce utilizatorul alege tipul instituției? Dacă e complicat să facem asta doar pentru mobil, putem s-o facem și pentru varianta desktop.

**Comment by LucianU** [comment]
@oliviavereha, poți confirma că funcționează acum? Ar trebui să se ascundă navigația când ești pe mobil.

**Comment by oliviavereha** [comment]
Merge doar dacă închid navigația. Am. Putea face sa apară un mesaj :
selectează instituția din lista de mai jos și închide navigația pentru a
vedea rezultatele.

Ca nu e obvious pentru oameni...

**Comment by LucianU** [comment]
Încearcă din nou, te rog, pentru mine a mers acum.

**Comment by oliviavereha** [comment]
Yes! it worked now. Thank you !! :D

_________________
0729990546

**Comment by LucianU** [comment]
Super. Fixed!
