### ISSUE TITLE
Lipsa informatii contextuale

### ISSUE THREAD

**Issue by oliviavereha** [code4romania/sna-client#63]
Chiar daca pentru oamenii specializati este evident, pentru mass audience, nu este. 
De exemplu, in paginile de tipul asta: https://sna.code4.ro/report/3/1/17?indicator_id=41
de prezentare generala trebuie sa adaugam deasupra un paragraf in care spunem la ce fac referire cifrele pe care le vad ei mai jos: 
Aceasta este situatia pe 2017 a ministerului Justitiei in ceea ce priveste cadourile.. something. 
Cred ca avem nevoie de un om de comunicare sa construiasca toate aceste texte si ele sa fie adaugate ca un summary sub titlurile trecute mari.

**Comment by LucianU** [comment]
Mai degrabă aș adăuga la Despre aplicație. Nu există riscul să trebuiască schimbat designul dacă vrem să adăugăm descrierile astea la fiecare indicator?
