### ISSUE TITLE
Adaugă un panou de loading

### ISSUE THREAD

**Issue by LucianU** [code4romania/sna-client#64]
Când un utilizator dă click pe o instituție și se încarcă datele de la server, nu există nici un feedback vizual. Pentru că durează mai mult de o secundă, ar prinde bine un indicator care să arate că datele se încarcă.

@calinrulz, te poți ocupa de asta?

**Comment by calinrulz** [comment]
@LucianU sigur

**Comment by LucianU** [comment]
Fixed.
