### ISSUE TITLE
Help tooltips for first time users

### ISSUE THREAD

**Issue by jsergiu** [code4romania/sna-client#7]
Store a cookie to check if a user is for the first time on the app

![image](https://cloud.githubusercontent.com/assets/4572368/23632017/ab408fec-02c0-11e7-8ab0-f81365ad74c3.png)

![image](https://cloud.githubusercontent.com/assets/4572368/23632027/b29c8d86-02c0-11e7-876d-ab738e83938a.png)

![image](https://cloud.githubusercontent.com/assets/4572368/23632042/bacc4a46-02c0-11e7-81aa-702be15f1e96.png)

**Comment by LucianU** [comment]
@kinkoazc is this complete, or there's still work to do?

**Comment by kinkoazc** [comment]
From my POV it's finished.
