### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by jsergiu** [code4romania/sna-client#9]
pagina despre aplicatie

**Comment by LucianU** [comment]
Redeschid pentru că am primit textul. Va rămâne doar pagina asta, fără pagina de Help.

> Strategia Națională Anticorupție (SNA) 2016-2020, adoptată prin Hotărârea Guvernului nr. 583/2016, este rezultatul unui îndelungat proces de consultare, care a avut în vedere concluziile auditului extern independent al SNA 2012-2015. Documentul strategic preia bunele practici implementate în cadrul SNA 2012-2015, respectiv misiunile de evaluare și platformele de cooperare, propunându-și totodată să îmbunătățească și să dezvolte unele aspecte.

> Scopul principal al acesteia este promovarea integrității în administrația publică, prin aplicarea riguroasă a cadrului normativ şi instituțional de prevenire și combatere a corupției în România.

> În acest context, pentru a înțelege mai bine procedura de monitorizare a implementării strategiei și rezultatele acesteia, a fost construită o aplicație interactivă prin intermediul căreia este evidențiată evoluția indicatorilor de evaluare într-un mod clar și util publicului interesat. Aplicația utilizează date cu caracter public, menite să creeze o imagine de ansamblu prin evidențierea informațiilor reale referitoare la evoluția indicatorilor de referință privind fenomenul de corupției din țara noastră, prin prisma laturii de prevenire a acesteia.

> De exemplu, pot fi vizualizate informațiile vizând respectarea cadrului normativ consultând evoluția indicatorilor de referință evidențiați pentru instituțiile din administrația publică la nivel național, local sau central.

@calinrulz, te poți ocupa de asta?

**Comment by calinrulz** [comment]
Salut @LucianU, sigur, ma pot ocupa eu de asta

**Comment by LucianU** [comment]
Mersi, @calinrulz!

**Comment by LucianU** [comment]
Implementat în #54.
